### ISSUE TITLE
Completion of lessons needs to be in another module, linked to user.

### ISSUE THREAD

**Issue by mark-bradshaw** [dallasbpeters/tiny-love#18]

**Comment by mark-bradshaw** [comment]
@dallasbpeters I've updated the module listing of lessons so that each one has a class of "uncompleted" or "completed".  I assume you'll want to do some styling for each state.

**Comment by dallasbpeters** [comment]
@mark-bradshaw I don't see this as tracking yet. I see the classes but they are not changing once I view them. Am I missing something?

**Comment by dallasbpeters** [comment]
fixed: https://github.com/dallasbpeters/tiny-love/commit/47c23dc3934c30e8a7421f085e3ea46eaaa5bb7d
