### ISSUE TITLE
Double check system emails design and function

### ISSUE THREAD

**Issue by dallasbpeters** [dallasbpeters/tiny-love#19]

**Comment by mark-bradshaw** [comment]
@dallasbpeters You can test the signup email by going to http://localhost:3001/keystone/test-email/signup.  That'll do a preview for you of what html will be sent out.

**Comment by mark-bradshaw** [comment]
Make sure you do a git pull first.

**Comment by dallasbpeters** [comment]
@mark-bradshaw I'm try to track down a real email address so that we can make sure real emails are in the codebase. I see several instances of tinylove@beadoula.com in there. I'm writing them an email now.
