### ISSUE TITLE
Supplemental Block should be conditional on content in field

### ISSUE THREAD

**Issue by dallasbpeters** [dallasbpeters/tiny-love#21]
This block should be conditional on whether or not the **supplemental** field has any content. see `lesson-layout.jade:18`

<img width="500" alt="screenshot 2015-07-16 15 28 52" src="https://cloud.githubusercontent.com/assets/91672/8734404/7380f91c-2bcf-11e5-896d-2c94d07921d3.png">

**Comment by mark-bradshaw** [comment]
Done #e76376a
