### ISSUE TITLE
Disable module link in dashboard if previous not completed

### ISSUE THREAD

**Issue by dallasbpeters** [dallasbpeters/tiny-love#22]
Per @mark-bradshaw: What I would suggest is doing this in jade. If the module status == 'disabled' then don't output the a tag.

**Comment by mark-bradshaw** [comment]
This is done now.  I'm not sure if you want to do additional styling for the list items with an anchor tag.

**Comment by dallasbpeters** [comment]
https://github.com/dallasbpeters/tiny-love/commit/fddabc248c9d7ab1e33a933b8ee0e3cebd0c2e28 closes this.
