### ISSUE TITLE
Consider attaching completion form answers to user model?

### ISSUE THREAD

**Issue by dallasbpeters** [dallasbpeters/tiny-love#23]
@mark-bradshaw what do you think about attaching the completion form fields to the user model for easy retrieval from the system without needing yet one more system bolted on? Just a thought. We can discuss.

**Comment by mark-bradshaw** [comment]
I can make sure that it's linked directly to the user record in any case.  Let me get that form all built out, and then maybe I'll just push it into a content field on the user.

**Comment by mark-bradshaw** [comment]
@dallasbpeters Can you send me a mockup for the survey, or a list of questions?

**Comment by dallasbpeters** [comment]
@mark-bradshaw if you log into the current app you can view...
The first two can be combined into one. 
- [Statement of Completion](https://onedrive.live.com/survey?resid=3CAC87F679CF00CD!112&authkey=!AJt2NZm3lezgLAA)
- [Standards of Practice Commitment Form](https://onedrive.live.com/survey?resid=3CAC87F679CF00CD!141&authkey=!AG5zf5l6j8BV6jo)

then after the first form we show this form...
- [Evaluation Form](https://onedrive.live.com/survey?resid=3CAC87F679CF00CD!147&authkey=!AI-WSIhDcansipo)

Hoping that we can view the responses in the user profile somehow + send the responses to J&K or admins? Would be sweet if they somehow lost that email to be able to pull up the user and see the responses. On top of the user responses, we need a central "report" that will show all the responses. Too much? Should we use a form system? Wufoo or similar?

**Comment by mark-bradshaw** [comment]
I'm leaving the last evaluation form in place at onedrive, and linking out to it.  It seems like a reasonable course at this point.
