### ISSUE TITLE
Add "edit Lesson" link to the user facing side

### ISSUE THREAD

**Issue by dallasbpeters** [dallasbpeters/tiny-love#24]
@mark-bradshaw for easy access we should figure out how to add an edit lesson link to the lesson.jade template. 

Keystone does it something like this: `.post(data-ks-editable=editable(user, { list: 'Post', id: post.id }))`

**Comment by mark-bradshaw** [comment]
I added editable links all over the place.  :)  It might be overkill.  If so let me know.
