### ISSUE TITLE
Implement a 404/505 page

### ISSUE THREAD

**Issue by dallasbpeters** [dallasbpeters/tiny-love#26]
@mark-bradshaw while testing the user/dashboard link while not signed in I was greeted with an ugly 505 page. We need to see if Keystone has default 404/505 templates that we can use or how to set some up.

**Comment by dallasbpeters** [comment]
actually the error I got was this: (sign out and visit **/user/dashboard**)

<img width="594" alt="screenshot 2015-07-16 17 06 33" src="https://cloud.githubusercontent.com/assets/91672/8736326/19e44bf8-2bdd-11e5-9da4-77ff1cb661e4.png">

**Comment by mark-bradshaw** [comment]
I've caught all 404s and redirected to / if you aren't logged in, and /user/dashboard if you are.  I think that basically fixes the issue.  More or less, 404s aren't possible, I think.

**Comment by dallasbpeters** [comment]
:+1:
