### ISSUE TITLE
Final TODOs

### ISSUE THREAD

**Issue by mark-bradshaw** [dallasbpeters/tiny-love#27]
- [x] Update from email address in signup.js.
- [ ] Switch to live Paypal.
- [x] Sign up for final Cloudinary and Mandrill accounts.
- [x] Migrate to final heroku account
- [x] Add course completion forms and flow.
- [x] Get GA account
- [x] Update email templates with final url + server.js line 84ish

**Comment by dallasbpeters** [comment]
Do you want to just stack them all up here @mark-bradshaw ? I think there will be quite a few more?

**Comment by mark-bradshaw** [comment]
Yeah, we can.  I just want to make sure I capture them somewhere.
