### ISSUE TITLE
Forgot Password functionality

### ISSUE THREAD

**Issue by dallasbpeters** [dallasbpeters/tiny-love#31]

**Comment by mark-bradshaw** [comment]
Done.  It could use a bit of style.

**Comment by dallasbpeters** [comment]
I tested with no emails. Would this work on local?

**Comment by mark-bradshaw** [comment]
The email sending is tied to my account right now.  That's one reason why
we need to get this setup with the correct Mandrill account for testing.

**Comment by mark-bradshaw** [comment]
I'll leave this open until we can get this working on a live Mandrill account.

**Comment by dallasbpeters** [comment]
@mark-bradshaw how difficult to just use send-grid? I say we do that if it's just as easy to make the swap.

**Comment by dallasbpeters** [comment]
This is dependent on #39 will wait until it's closed.

**Comment by mark-bradshaw** [comment]
Mandrill is setup, but there's a temporary hold on the account right now.  I've switched the code over to use the correct sending address, so once the hold is off we can do a final test on this.

**Comment by dallasbpeters** [comment]
Awesome!

**Comment by mark-bradshaw** [comment]
The hold is off, so this should be testable now @dallasbpeters

**Comment by mark-bradshaw** [comment]
Just tested.  Worked like a charm.  The email I got had a broken image link up top though.

**Comment by mark-bradshaw** [comment]
So I think the problem is that emails are referencing the web layouts, which is fine, but those web layouts reference things with relative paths.  /images/logo-white.svg instead of http://www.beadoula.com/images/logo-white.svg.  I think we either need to change those links to absolute paths, or get a different set of layouts for emails.

**Comment by mark-bradshaw** [comment]
@dallasbpeters thoughts on ^^

**Comment by dallasbpeters** [comment]
Putting full path in is fine. Though that is odd because Keystone used an image in that directory by default I believe.

**Comment by mark-bradshaw** [comment]
The problem is that the relative path is computed based on the email
client.  So they always have to be absolute.

**Comment by mark-bradshaw** [comment]
But we can have a different set of templates for email, and that might not
be a bad idea.  Keep it simple.
