### ISSUE TITLE
Cloudinary small?

### ISSUE THREAD

**Issue by dallasbpeters** [dallasbpeters/tiny-love#37]
@mark-bradshaw from the keystone repo https://github.com/keystonejs/keystone/issues/93

> We've been talking to Cloudinary about this and they've created a 'small' plan for KeystoneJS and Wordpress users. It's not available generally on their 'pricing' page, but after signing up for a free account you can use this URL to get access to it:
> 
> https://cloudinary.com/users/upgrade/small
> 
> It costs $10/month and includes 2 GB Storage, 100,000 Images and 10 GB Monthly Bandwidth - which is a big improvement over the free plan, and hopefully not out of the ballpark for smaller sites.
> 
> I'll include a link to it in the docs, also.

**Comment by mark-bradshaw** [comment]
Perfect!

**Comment by dallasbpeters** [comment]
@mark-bradshaw Cloudinary has been set up using the default user/pass. We can see how long the free plan gets us buy or go ahead and suggest the small plan upgrade.
