### ISSUE TITLE
Mark lesson complete when the next button is hit.

### ISSUE THREAD

**Issue by mark-bradshaw** [dallasbpeters/tiny-love#38]

**Comment by mark-bradshaw** [comment]
I've added code to mark a lesson complete when you push the Next Lesson or Dashboard button.  That's working normally, but I see that there's something odd happening in the third module with lesson ordering.  Haven't tracked it down yet.  Could be a data issue.

I added some styling to the lesson progress bar down below to indicate lessons that are complete and lessons that are not.  You'll want to take a look at that and change it.

**Comment by dallasbpeters** [comment]
Complete: https://github.com/dallasbpeters/tiny-love/commit/47c23dc3934c30e8a7421f085e3ea46eaaa5bb7d
