### ISSUE TITLE
Move hosted resources

### ISSUE THREAD

**Issue by dallasbpeters** [dallasbpeters/tiny-love#42]
- [x] Get resources
- [x] Move resources
- [x] Determine hosting solution

@mark-bradshaw there are some hosted resources (pdfs, etc) that are on the current site. We will need to determine a solution for that bit. I'm working on getting access to the web server so I can download them in bulk.

**Comment by dallasbpeters** [comment]
@mark-bradshaw how are we going to host these assets? PDFs mainly.

**Comment by mark-bradshaw** [comment]
Let's just add them to the repo, if they aren't that big.  What sort of size?

**Comment by mark-bradshaw** [comment]
@dallasbpeters Did you ever get direct access to the old server for direct downloading?
