### ISSUE TITLE
Complete Module Bug

### ISSUE THREAD

**Issue by dallasbpeters** [dallasbpeters/tiny-love#45]
@mark-bradshaw hey man, ran across this bug we need to get worked out. I propose:
- The complete button should be smarter so that it doesn't say complete/ is disabled
- The better would be that the dots ahead of where you are are not in fact clickable. 

Thoughts?

<img width="976" alt="screenshot 2015-07-28 15 46 59" src="https://cloud.githubusercontent.com/assets/91672/8943326/f0489292-353f-11e5-9d09-dbff5500bebe.png">

**Comment by dallasbpeters** [comment]
@mark-bradshaw can you just put some logic in the view `lesson-layout.jade:33` and I can tweak it out later and think about how to handle the links/diabled/etc?

**Comment by mark-bradshaw** [comment]
I've updated the module lesson list and the lesson footer nav so that in both cases only lessons that are completed and the current lesson are linked.  All further uncompleted lessons are not linked.
