### ISSUE TITLE
Connect to Real PayPal account

### ISSUE THREAD

**Issue by dallasbpeters** [dallasbpeters/tiny-love#46]

**Comment by mark-bradshaw** [comment]
Waiting for Kristen to upgrade to business account.

**Comment by mark-bradshaw** [comment]
I've got the real paypal account in there, but have yet to test it.  Caution if you sign up a new account.  You're playing with real money.

**Comment by mark-bradshaw** [comment]
This is tested, and one.  I set the course amount to $460, like was on the old site.

**Comment by dallasbpeters** [comment]
Awesome! Do we know if there is a way to setup promo codes for this @mark-bradshaw ? Just curious.

**Comment by mark-bradshaw** [comment]
Hmm..  Well, the price is controlled by paypal, but I don't recall an
option for promo codes.  I just double checked and it's not there.  My best
suggestion is that if you want a promotional price we create a second
button, with the reduced price, and put it at a hidden url.

**Comment by dallasbpeters** [comment]
Cool!
