### ISSUE TITLE
Keystone allows multiple users

### ISSUE THREAD

**Issue by dallasbpeters** [dallasbpeters/tiny-love#50]
@mark-bradshaw well crap, I was creating accounts for the ladies and ended up creating multiple accounts with no errors. I sure would hate for this to some how spill out on users and result in errors or duplicated accounts. We need to track that down??

**Comment by mark-bradshaw** [comment]
Did you do that via the signup form, because it checks for duplicate email addresses?  My guess is either you were using the admin interface, which bypasses those checks, or you used the live site and maybe it had old code.  I'm going to retest.

**Comment by dallasbpeters** [comment]
I did in the admin. Creating accounts for the girls and somehow they already had accounts.

**Comment by mark-bradshaw** [comment]
That explains it.
