### ISSUE TITLE
App is suuuuuuper slow.

### ISSUE THREAD

**Issue by dallasbpeters** [dallasbpeters/tiny-love#53]
@mark-bradshaw we might need to investigate here. The app is really, really slow on the initial payload.

**Comment by mark-bradshaw** [comment]
The reason for this is taht the heroku app is still using a free dyno.  Free dynos go to sleep when they aren't used for 30 minutes, and if they are up for 18 hours straight, they have to shut down for six.  That's how they make you pay.  :)  Kristen needs to go ahead and pay for a dyno and then the site will stay up, and first response will pick back up.
