### ISSUE TITLE
Sorting Lessons

### ISSUE THREAD

**Issue by dallasbpeters** [dallasbpeters/tiny-love#54]
@mark-bradshaw I'm scrambling on some other things but wondering if you might have a moment this evening to track down the sort issue that Jessica is having. There are a few other complaints in the community:

https://github.com/keystonejs/keystone/issues/1439
https://github.com/keystonejs/keystone/issues/623
https://github.com/keystonejs/keystone/issues/441

Let me know if you have time to chat about it this evening!

**Comment by mark-bradshaw** [comment]
This is fixed now.  I had a screwed up configuration in the Module and Lesson.

**Comment by dallasbpeters** [comment]
Awesome man! Thanks for carving out some time!
