### ISSUE TITLE
Get Certificate Button

### ISSUE THREAD

**Issue by dallasbpeters** [dallasbpeters/tiny-love#56]
@mark-bradshaw we should only show the "Get My Certificate" button on the dash board if the user has not filled out the completion form. Right? Once they fill out the form they should not see that button anymore. I thought about copying the `if showSurvey` from `complete.jade` but wasn't sure if that was available. Thought you might be able to bang it out quicker.

**Comment by dallasbpeters** [comment]
Oh, now I'm wondering if we don't swap out that button (once they fill out the form) with the survey button? Thoughts?

**Comment by mark-bradshaw** [comment]
I thought they had to finish the survey before getting the certificate?

**Comment by dallasbpeters** [comment]
Hmm... I was thinking it was optional. But maybe not. I just saw that the survey was on the same page at the form and wondered how they would see it?

**Comment by mark-bradshaw** [comment]
Done.  After you fill out the completion survey it'll show the survey link on the dashboard.
