### ISSUE TITLE
Certificate form needs validation

### ISSUE THREAD

**Issue by dallasbpeters** [dallasbpeters/tiny-love#57]
@mark-bradshaw I just filled out the form with only one check and one signature. :) Guess we need to validate that form.

**Comment by dallasbpeters** [comment]
@mark-bradshaw any time to have a peek at this?

**Comment by mark-bradshaw** [comment]
I'll see if I can hit that tonight

**Comment by mark-bradshaw** [comment]
I found a few of the form fields didn't have the required attribute.  I've added it all around, and it seems to be validating properly.  Please retest.
