### ISSUE TITLE
Can't sign up

### ISSUE THREAD

**Issue by dallasbpeters** [dallasbpeters/tiny-love#9]
@mark-bradshaw I wasn't sure if you were aware or not that accounts don't seem to be able to be created. Have a peek at these shots. Maybe you already know about it. 

![screenshot 2015-06-29 22 51 50](https://cloud.githubusercontent.com/assets/91672/8423619/91a81676-1eb1-11e5-90b7-2040b6315469.png)
![screenshot 2015-06-29 22 51 57](https://cloud.githubusercontent.com/assets/91672/8423620/91a940d2-1eb1-11e5-8322-a6292d20f9cb.png)

**Comment by dallasbpeters** [comment]
Oh, I just saw the https://github.com/dallasbpeters/tiny-love/tree/signup branch. Guessing that was were the work was being done. Should we get that merged in?

**Comment by mark-bradshaw** [comment]
That bug was fixed last night by setting line 15 in models/User.js.  That will take care of that.

The signup branch was already merged in so I went ahead and deleted it.
